### ISSUE TITLE
Confirmação atendimentos

### ISSUE THREAD

**Issue by adrianomelo** [colabore/iluminare#235]
Teríamos como amarrar a lógica de mudança de salas na base? Eu não estou entendendo a lógica de como fazer os redirecionamentos e não sei se a informação do dia do tratamento está sendo usada.

Possíveis issues relacionadas: #230 #220

Estou trabalhando na tela de confirmação de atendimento. Pelo o que eu entendi do código abaixo, vc encaminha para algum tratamento do mesmo dia, certo?

``` python
# https://github.com/colabore/iluminare/blob/experimental/src/iluminare/atendimento/views.py#L432
        # CAREREGA O CAMPO REDIRECIONA
        lista_segunda = [7,11,12,13]
        lista_quinta = [1,2,3,4,5,14]
        if tratamento.id in lista_quinta:
            lista_quinta.remove(tratamento.id)
            self.fields['redireciona'].queryset=Tratamento.objects.filter(id__in=lista_quinta)
        elif tratamento.id in lista_segunda:
            lista_segunda.remove(tratamento.id)
            self.fields['redireciona'].queryset=Tratamento.objects.filter(id__in=lista_segunda)
        elif tratamento.id == 6:
            self.fields['redireciona'].queryset=Tratamento.objects.none()
            opcoes = (('X','---------'),) + Paciente.FREQUENCIA
        else:
            self.fields['redireciona'].queryset=Tratamento.objects.none()
```

**Comment by guilhermeamorim** [comment]
Fala Adriano,
Temos 2 grupos de tratamentos: o da segunda o da quinta. O que fazemos é verificar se o tratamento em questão (tratamento.id) está na lista da quinta. Se tiver, ele é retirado na lista (lista_quinta) e atualizamos o campo redireciona de maneira a conter a lista_quinta sem o tratamento.id. Com isso, evitamos que seja realizado um redirecionamento para o mesmo tratamento em questão. O mesmo é feito para a lista_segunda. No caso do tratamento de id=6, não é possível haver redirecionamento.
Qq dúvida me fala.
Abc
